projet_test1_yml_homepage:
    path:     /
    defaults: { _controller: projetTest1YMLBundle:Default:index }

maRoute1SurPage1:
    path:     /mapage1Test
    defaults: { _controller: projetTest1YMLBundle:Default:affichagePage1 }

maRoute1SurPage2:
      path:     /mapage2Test
      defaults: { _controller: projetTest1YMLBundle:Default:affichagePage2 }
      methods:  [GET]

maRoute2SurPage2:
    path:     /mapage2Test/{param}
    defaults: { _controller: projetTest1YMLBundle:Default:affichagePage2, param : 'une valeur par défaut dans la route' }
    methods:  [GET]

maRoute3SurPage2:
    path:     /mapage2Test
    defaults: { _controller: projetTest1YMLBundle:Default:affichagePage2form }
    methods:  [POST]

maRoute4SurPage2:
    path:     /mapage2Test
    defaults: { _controller: projetTest1YMLBundle:Default:affichagePage2form }
    methods:  [PUT]